
// CIRCUITAL...
class CSE {
  List<String> sem1 = ['BECE', 'BME', 'CHEMISTRY', 'MATHEMATICS - I'];

  List<String> sem2 = ['BEE', 'MATHEMATICS - II', 'PPS', 'PHYSICS'];

  List<String> sem3 = ['BIC', 'BSE', 'DISCRETE MATHEMATICS', 'DIGITAL SYSTEM DESIGN', 'DATA STRUCTURE'];

  List<String> sem4 = ['COA', 'DAA', 'ENVIRONMENTAL SCIENCE', 'NUMERICAL METHODS', 'OOPDP', 'OPERATING SYSTEM'];
}

class IT {
  List<String> sem1 = ['BECE', 'BME', 'CHEMISTRY', 'MATHEMATICS - I'];

  List<String> sem2 = ['BEE', 'MATHEMATICS - II', 'PPS', 'PHYSICS'];

  List<String> sem3 = ['BIC', 'BSE', 'DISCRETE MATHEMATICS', 'DIGITAL SYSTEM DESIGN', 'DATA STRUCTURE'];

  List<String> sem4 = ['COA', 'DAA', 'ENVIRONMENTAL SCIENCE', 'NUMERICAL METHODS',
    'OOPDP', 'OPERATING SYSTEM',];
}

class ECE {
  List<String> sem1 = ['BECE', 'BME', 'CHEMISTRY', 'MATHEMATICS - I'];

  List<String> sem2 = ['BEE', 'MATHEMATICS - II', 'PPS', 'PHYSICS'];

  List<String> sem3 = ['BIC', 'BSE', 'CIRCUIT THEORY', 'DIGITAL SYSTEM DESIGN', 'ELECTRONIC DEVICE', 'SIGNALS AND SYSTEM'];

  List<String> sem4 = ['ANALOG CIRCUITS', 'ANALOG COMMUNICATION', 'EMF AND WAVES', 'ENVIRONMENTAL SCIENCE',
    'NUMERICAL METHODS', 'PROBABILITY & RANDOM PROCESSES'];
}

class EEE {
  List<String> sem1 = ['BECE', 'BME', 'CHEMISTRY', 'MATHEMATICS - I'];

  List<String> sem2 = ['BEE', 'MATHEMATICS - II', 'PPS', 'PHYSICS'];

  List<String> sem3 = ['BIC', 'BSE', 'CIRCUIT THEORY', 'DIGITAL SYSTEM DESIGN', 'ELECTRICAL ENERGY GENERATION & CONTROL',
    'ELECTRICAL MEASUREMENT AND INSTRUMENTATION'];

  List<String> sem4 = [
    'DC MACHINES AND TRANSFORMERS', 'ENGINEERING ELECTROMAGNETICS', 'ENVIRONMENTAL SCIENCE', 'NUMERICAL METHODS',
    /*'OPEN ELECTIVE - I'*/];
}

// NON CIRCUITAL...
class MECH {
  List<String> sem1 = ['BEE', 'MATHEMATICS - II', 'PPS', 'PHYSICS'];

  List<String> sem2 = ['BECE', 'BME', 'CHEMISTRY', 'MATHEMATICS - I'];

  List<String> sem3 = ['ENVIRONMENTAL SCIENCE', 'FLUID MECHANICS & HYDRAULIC MACHINES', 'MANUFACTURING PROCESSES',
    'NUMERICAL METHODS', 'THERMODYNAMICS', 'STRENGTH OF MATERIAL'];

  List<String> sem4 = ['BIC', 'BSE', 'ENERGY CONVERSION SYSTEM', 'KINEMATICS & DYNAMICS OF MACHINES',
    'MACHINE DESIGN', /*'PROGRAM ELECTIVE - I'*/];
}

class CIV {
  List<String> sem1 = ['BEE', 'MATHEMATICS - II', 'PPS', 'PHYSICS'];

  List<String> sem2 = ['BECE', 'BME', 'CHEMISTRY', 'MATHEMATICS - I'];

  List<String> sem3 = ['BUILDING MATERIALS AND CONSTRUCTION', 'ENVIRONMENTAL SCIENCE', 'FLUID MECHANICS',
    'NUMERICAL METHODS', 'FLUID MECHANICS', 'STRUCTURAL ANALYSIS - I'];

  List<String> sem4 = ['BIC', 'BSE', 'CONSTRUCTION ENGINEERING AND MANAGEMENT',
    'EARTHQUAKE AND DISASTER MANAGEMENT', 'STRUCTURAL ANALYSIS - II', 'SURVEYING'];
}

class CHEM {
  List<String> sem1 = ['BEE', 'MATHEMATICS - II', 'PPS', 'PHYSICS'];

  List<String> sem2 = ['BECE', 'BME', 'CHEMISTRY', 'MATHEMATICS - I'];

  List<String> sem3 = ['CHEMICAL PRINCIPLES FOR CHEMICAL ENGINEERS', 'CHEMICAL PROCESS CALCULATIONS',
    'ENVIRONMENTAL SCIENCE', 'FLUID MECHANICS', 'MECHANICAL OPERATOR', 'NUMERICAL METHODS', 'THERMODYNAMICS'];

  List<String> sem4 = ['BIC', 'BSE', 'HEAT TRANSFER OPERATIONS', 'MASS TRANSFER OPERATIONS - I',
  'PROCESS TECHNOLOGY & ECONOMICS',  'TRANSPORT PHENOMENA' /*'OPEN ELECTIVE - I'*/];
}

class CPP {
  List<String> sem1 = ['BEE', 'MATHEMATICS - II', 'PPS', 'PHYSICS'];

  List<String> sem2 = ['BECE', 'BME', 'CHEMISTRY', 'MATHEMATICS - I'];

  List<String> sem3 = ['CHEMICAL PROCESS CALCULATIONS', 'ENVIRONMENTAL SCIENCE', 'FLUID MECHANICS',
    'MACROMOLECULAR SCIENCE', 'MECHANICAL OPERATIONS', 'NUMERICAL METHODS', 'THERMODYNAMICS'];

  List<String> sem4 = ['BIC', 'BSE', 'PROCESS TECHNOLOGY & ECONOMICS - I', 'HEAT TRANSFER OPERATIONS',
    'MASS TRANSFER OPERATIONS', 'POLYMER TECHNOLOGY', /*'OPEN ELECTIVE - I'*/];
}

class PROD {
  List<String> sem1 = ['BEE', 'MATHEMATICS - II', 'PPS', 'PHYSICS'];

  List<String> sem2 = ['BECE', 'BME', 'CHEMISTRY', 'MATHEMATICS - I'];

  List<String> sem3 = ['FLUID MECHANICS AND HYDRAULIC MACHINES', 'ENVIRONMENTAL SCIENCE', 'METALLURGY',
    'NUMERICAL METHODS', 'OPERATIONAL RESEARCH', 'STRENGTH OF MATERIAL'];

  List<String> sem4 = ['BIC', 'BSE', 'MANUFACTURING PROCESS - I', 'METROLOGY AND MEASUREMENT',
    'KINEMATICS AND DYNAMICS OF MACHINES', /*'PROGRAM ELECTIVE - I'*/];
}

class BIO {
  List<String> sem1 = ['BEE', 'MATHEMATICS - II', 'PPS', 'PHYSICS'];

  List<String> sem2 = ['BECE', 'BME', 'CHEMISTRY', 'MATHEMATICS - I'];

  List<String> sem3 = ['BASICS OF BIOINFORMATICS', 'BIOCHEMISTRY AND ENZYME TECHNOLOGY',
    'CELL AND MOLECULAR BIOLOGY', 'CHEMICAL PROCESS CALCULATIONS', 'ENVIRONMENTAL SCIENCE',
    'MICROBIOLOGY', 'NUMERICAL METHODS',];

  List<String> sem4 = ['BIC', 'BSE', 'BIOLOGY OF IMUNE SYSTEM', 'FLUID MECHANICS AND HEAT TRANSFER',
    'THERMO OF CHEMICAL AND BIOLOGICAL SYSTEMS', /*Text('PROGRAMME ELECTIVE - I'), 'OPEN ELECTIVE - I'*/];
}
