import 'package:flutter/material.dart';

// CIRCUITAL...
class CSE {
  List<Widget> sem1 = [
    Text('BASICS OF ELECTRONICS AND COMMUNICATION ENGINEERING'),
    Text('BASICS OF MECHANICAL ENGINEERING'),
    Text('CHEMISTRY'),
    Text('MATHEMATICS I')
  ];

  List<Widget> sem2 = [
    Text('BASICS OF ELECTRICAL ENGINEERING'),
    Text('MATHEMATICS II'),
    Text('PROGRAMMING FOR PROBLEM SOLVING'),
    Text('PHYSICS')
  ];

  List<Widget> sem3 = [
    Text('BASICS OF INTELLIGENT COMPUTING'),
    Text('BIOLOGICAL SCIENCE FOR ENGINEERS'),
    Text('DISCRETE MATHEMATICS'),
    Text('DIGITAL SYSTEM DESIGN'),
    Text('DATA STRUCTURE')
  ];

  List<Widget> sem4 = [
    Text('COMPUTER ORGANIZATION ARCHITECTURE'),
    Text('DESIGN ANALYSIS OF ALGORITHM'),
    Text('ENVIRONMENTAL SCIENCE'),
    Text('NUMERICAL METHODS'),
    Text('OBJECT ORIENTED PROGRAMMING AND DESIGN PATTERN'),
    Text('OPERATING SYSTEM')
  ];
}

class IT {
  List<Widget> sem1 = [
    Text('BASICS OF ELECTRONICS AND COMMUNICATION ENGINEERING'),
    Text('BASICS OF MECHANICAL ENGINEERING'),
    Text('CHEMISTRY'),
    Text('MATHEMATICS I')
  ];

  List<Widget> sem2 = [
    Text('BASICS OF ELECTRICAL ENGINEERING'),
    Text('MATHEMATICS II'),
    Text('PROGRAMMING FOR PROBLEM SOLVING'),
    Text('PHYSICS')
  ];

  List<Widget> sem3 = [
    Text('BASICS OF INTELLIGENT COMPUTING'),
    Text('BIOLOGICAL SCIENCE FOR ENGINEERS'),
    Text('DISCRETE MATHEMATICS'),
    Text('DIGITAL SYSTEM DESIGN'),
    Text('DATA STRUCTURE')
  ];

  List<Widget> sem4 = [
    Text('COMPUTER ORGANIZATION ARCHITECTURE'),
    Text('DESIGN ANALYSIS OF ALGORITHM'),
    Text('ENVIRONMENTAL SCIENCE'),
    Text('NUMERICAL METHODS'),
    Text('OBJECT ORIENTED PROGRAMMING AND DESIGN PATTERN'),
    Text('OPERATING SYSTEM')
  ];
}

class ECE {
  List<Widget> sem1 = [
    Text('BASICS OF ELECTRONICS AND COMMUNICATION ENGINEERING'),
    Text('BASICS OF MECHANICAL ENGINEERING'),
    Text('CHEMISTRY'),
    Text('MATHEMATICS I')
  ];

  List<Widget> sem2 = [
    Text('BASICS OF ELECTRICAL ENGINEERING'),
    Text('MATHEMATICS II'),
    Text('PROGRAMMING FOR PROBLEM SOLVING'),
    Text('PHYSICS')
  ];

  List<Widget> sem3 = [
    Text('BASICS OF INTELLIGENT COMPUTING'),
    Text('BIOLOGICAL SCIENCE FOR ENGINEERS'),
    Text('CIRCUIT THEORY'),
    Text('DIGITAL SYSTEM DESIGN'),
    Text('ELECTRONIC DEVICE'),
    Text('SIGNALS AND SYSTEM')
  ];

  List<Widget> sem4 = [
    Text('ANALOG CIRCUITS'),
    Text('ANALOG COMMUNICATION'),
    Text('ELECTROMAGNETIC FIELDS AND WAVES'),
    Text('ENVIRONMENTAL SCIENCE'),
    Text('NUMERICAL METHODS'),
    Text('PROBABILITY AND RANDOM PROCESSES')
  ];
}

class EEE{
  List<Widget> sem1 = [
    Text('BASICS OF ELECTRONICS AND COMMUNICATION ENGINEERING'),
    Text('BASICS OF MECHANICAL ENGINEERING'),
    Text('CHEMISTRY'),
    Text('MATHEMATICS I')
  ];

  List<Widget> sem2 = [
    Text('BASICS OF ELECTRICAL ENGINEERING'),
    Text('MATHEMATICS II'),
    Text('PROGRAMMING FOR PROBLEM SOLVING'),
    Text('PHYSICS')
  ];

  List<Widget> sem3 = [
    Text('BASICS OF INTELLIGENT COMPUTING'),
    Text('BIOLOGICAL SCIENCE FOR ENGINEERS'),
    Text('CIRCUIT THEORY'),
    Text('DIGITAL SYSTEM DESIGN'),
    Text('ELECTRICAL ENERGY GENERATION & CONTROL'),
    Text('ELECTRICAL MEASUREMENT AND INSTRUMENTATION')
  ];

  List<Widget> sem4 = [
    Text('DC MACHINES AND TRANSFORMERS'),
    Text('ENGINEERING ELECTROMAGNETICS'),
    Text('ENVIRONMENTAL SCIENCE'),
    Text('NUMERICAL METHODS')
    //Text('OPEN ELECTIVE - I')
  ];
}


// NON CIRCUITAL...
class MECH {
  List<Widget> sem1 = [
    Text('BASICS OF ELECTRICAL ENGINEERING'),
    Text('MATHEMATICS II'),
    Text('PROGRAMMING FOR PROBLEM SOLVING'),
    Text('PHYSICS')
  ];

  List<Widget> sem2 = [
    Text('BASICS OF ELECTRONICS AND COMMUNICATION ENGINEERING'),
    Text('BASICS OF MECHANICAL ENGINEERING'),
    Text('CHEMISTRY'),
    Text('MATHEMATICS I')
  ];

  List<Widget> sem3 = [
    Text('ENVIRONMENTAL SCIENCE'),
    Text('FLUID MECHANICS & HYDRAULIC MACHINES'),
    Text('MANUFACTURING PROCESSES'),
    Text('NUMERICAL METHODS'),
    Text('THERMODYNAMICS'),
    Text('STRENGTH OF MATERIAL')
  ];

  List<Widget> sem4 = [
    Text('BASICS OF INTELLIGENT COMPUTING'),
    Text('BIOLOGICAL SCIENCE FOR ENGINEERS'),
    Text('ENERGY CONVERSION SYSTEM'),
    Text('KINEMATICS & DYNAMICS OF MACHINES'),
    Text('MACHINE DESIGN')
    //Text('PROGRAM ELECTIVE - I')
  ];
}

class  CIV{
  List<Widget> sem1 = [
    Text('BASICS OF ELECTRICAL ENGINEERING'),
    Text('MATHEMATICS II'),
    Text('PROGRAMMING FOR PROBLEM SOLVING'),
    Text('PHYSICS')
  ];

  List<Widget> sem2 = [
    Text('BASICS OF ELECTRONICS AND COMMUNICATION ENGINEERING'),
    Text('BASICS OF MECHANICAL ENGINEERING'),
    Text('CHEMISTRY'),
    Text('MATHEMATICS I')
  ];

  List<Widget> sem3 = [
    Text('BUILDING MATERIALS AND CONSTRUCTION'),
    Text('ENVIRONMENTAL SCIENCE'),
    Text('FLUID MECHANICS'),
    Text('NUMERICAL METHODS'),
    Text('SOLID MECHANICS'),
    Text('STRUCTURAL ANALYSIS - I')
  ];

  List<Widget> sem4 = [
  Text('BASICS OF INTELLIGENT COMPUTING'),
  Text('BIOLOGICAL SCIENCE FOR ENGINEERS'),
  Text('CONSTRUCTION ENGINEERING AND MANAGEMENT'),
  Text('EARTHQUAKE ENGINEERING AND DISASTER MANAGEMENT'),
  Text('STRUCTURAL ANALYSIS - II'),
  Text('SURVEYING')
  ];
}

class  CHEM{
  List<Widget> sem1 = [
    Text('BASICS OF ELECTRICAL ENGINEERING'),
    Text('MATHEMATICS II'),
    Text('PROGRAMMING FOR PROBLEM SOLVING'),
    Text('PHYSICS')
  ];

  List<Widget> sem2 = [
    Text('BASICS OF ELECTRONICS AND COMMUNICATION ENGINEERING'),
    Text('BASICS OF MECHANICAL ENGINEERING'),
    Text('CHEMISTRY'),
    Text('MATHEMATICS I')
  ];

  List<Widget> sem3 = [
    Text('CHEMICAL PRINCIPLES FOR CHEMICAL ENGINEERS'),
    Text('CHEMICAL PROCESS CALCULATIONS'),
    Text('ENVIRONMENTAL SCIENCE'),
    Text('FLUID MECHANICS'),
    Text('MECHANICAL OPERATOR'),
    Text('NUMERICAL METHODS'),
    Text('THERMODYNAMICS')
  ];

  List<Widget> sem4 = [
    Text('BASICS OF INTELLIGENT COMPUTING'),
    Text('BIOLOGICAL SCIENCE FOR ENGINEERS'),
    Text('HEAT TRANSFER OPERATIONS'),
    Text('MASS TRANSFER OPERATIONS - I'),
    Text('PROCESS TECHNOLOGY & ECONOMICS'),
    Text('TRANSPORT PHENOMENA')
    //Text('OPEN ELECTIVE - I')
  ];
}

class  CPP{
  List<Widget> sem1 = [
    Text('BASICS OF ELECTRICAL ENGINEERING'),
    Text('MATHEMATICS II'),
    Text('PROGRAMMING FOR PROBLEM SOLVING'),
    Text('PHYSICS')
  ];

  List<Widget> sem2 = [
    Text('BASICS OF ELECTRONICS AND COMMUNICATION ENGINEERING'),
    Text('BASICS OF MECHANICAL ENGINEERING'),
    Text('CHEMISTRY'),
    Text('MATHEMATICS I')
  ];

  List<Widget> sem3 = [
    Text('CHEMICAL PROCESS CALCULATIONS'),
    Text('ENVIRONMENTAL SCIENCE'),
    Text('FLUID MECHANICS'),
    Text('MACROMOLECULAR SCIENCE'),
    Text('MECHANICAL OPERATIONS'),
    Text('NUMERICAL METHODS'),
    Text('THERMODYNAMICS')
  ];

  List<Widget> sem4 = [
    Text('BASICS OF INTELLIGENT COMPUTING'),
    Text('BIOLOGICAL SCIENCE FOR ENGINEERS'),
    Text('PROCESS TECHNOLOGY & ECONOMICS - I'),
    Text('HEAT TRANSFER OPERATIONS'),
    Text('MASS TRANSFER OPERATIONS'),
    Text('POLYMER TECHNOLOGY'),
    //Text('OPEN ELECTIVE - I')
  ];
}

class  PROD{
  List<Widget> sem1 = [
    Text('BASICS OF ELECTRICAL ENGINEERING'),
    Text('MATHEMATICS II'),
    Text('PROGRAMMING FOR PROBLEM SOLVING'),
    Text('PHYSICS')
  ];

  List<Widget> sem2 = [
    Text('BASICS OF ELECTRONICS AND COMMUNICATION ENGINEERING'),
    Text('BASICS OF MECHANICAL ENGINEERING'),
    Text('CHEMISTRY'),
    Text('MATHEMATICS I')
  ];

  List<Widget> sem3 = [
    Text('FLUID MECHANICS AND HYDRAULIC MACHINES'),
    Text('ENVIRONMENTAL SCIENCE'),
    Text('METALLURGY'),
    Text('NUMERICAL METHODS'),
    Text('OPERATIONAL RESEARCH'),
    Text('STRENGTH OF MATERIAL')
  ];

  List<Widget> sem4 = [
    Text('BASICS OF INTELLIGENT COMPUTING'),
    Text('BIOLOGICAL SCIENCE FOR ENGINEERS'),
    Text('MANUFACTURING PROCESS - I'),
    Text('METROLOGY AND MEASUREMENT'),
    Text('KINEMATICS AND DYNAMICS OF MACHINES'),
    //Text('PROGRAM ELECTIVE - I')
  ];
}

class  BIO{
  List<Widget> sem1 = [
    Text('BASICS OF ELECTRICAL ENGINEERING'),
    Text('MATHEMATICS II'),
    Text('PROGRAMMING FOR PROBLEM SOLVING'),
    Text('PHYSICS')
  ];

  List<Widget> sem2 = [
    Text('BASICS OF ELECTRONICS AND COMMUNICATION ENGINEERING'),
    Text('BASICS OF MECHANICAL ENGINEERING'),
    Text('CHEMISTRY'),
    Text('MATHEMATICS I')
  ];

  List<Widget> sem3 = [
    Text('BASICS OF BIOINFORMATICS'),
    Text('BIOCHEMISTRY AND ENZYME TECHNOLOGY'),
    Text('CELL AND MOLECULAR BIOLOGY'),
    Text('CHEMICAL PROCESS CALCULATIONS'),
    Text('ENVIRONMENTAL SCIENCE'),
    Text('MICROBIOLOGY'),
    Text('NUMERICAL METHODS')
  ];

  List<Widget> sem4 = [
    Text('BASICS OF INTELLIGENT COMPUTING'),
    Text('BIOLOGICAL SCIENCE FOR ENGINEERS'),
    Text('BIOLOGY OF IMUNE SYSTEM'),
    Text('FLUID MECHANICS AND HEAT TRANSFER'),
    Text('THERMODYNAMICS OF CHEMICAL AND BIOLOGICAL SYSTEMS'),
    //Text('PROGRAMME ELECTIVE - I'),
    //Text('OPEN ELECTIVE - I')
  ];
}